services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    env_file: ".env.deploy"
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - proxiable
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod", "-u", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  thevoid:
    container_name: thevoid
    build:
      context: .
      secrets:
        - env
      args:
        DATABASE_URL: ${DATABASE_URL}
    env_file: ".env.deploy"
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /src
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proxiable
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - type: bind
        source: /etc/letsencrypt/
        target: /etc/letsencrypt/
      - type: bind
        source: /var/www/certbot/
        target: /var/www/certbot/
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - thevoid
    networks:
      - proxiable
  certbot:
    image: certbot/certbot:latest
    volumes:
      - type: bind
        source: /etc/letsencrypt/
        target: /etc/letsencrypt/
      - type: bind
        source: /var/www/certbot/
        target: /var/www/certbot/
volumes:
  pgdata:
  database:
  letsencrypt:
  certbot:

secrets:
  env:
    file: "./.env.deploy"

networks:
  proxiable:
    name: proxiable
